---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-react
  labels:
    app: todo-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-react
  template:
    metadata:
      name: todo-react
      labels:
        app: todo-react
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - todo-react
              topologyKey: "kubernetes.io/hostname"

      containers:
        - name: todo-react
          image: cr.yandex/crpd55fmd7bksog5p7vd/todo-react:d9b030ce9ac5fd96d350b34a2769cd6412b1addf
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
---
### Service
apiVersion: v1
kind: Service
metadata:
  name: todo-react
spec:
  selector:
    app: todo-react
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: LoadBalancer
---
### HPA
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-react
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-react
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 15