on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v6

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Retrieve secrets & JKS
        id: jks
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          echo ${{ secrets.JKS_BASE64 }} | base64 -d - > keystore.jks

      - name: Build, tag, and push image
        id: docker-build
        env:
          CR_REGISTRY: crpd55fmd7bksog5p7vd
          CR_REPOSITORY: todo-react
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.35.4'

      - name: Set up Yandex Cloud CLI
        uses: okar1/yc-cli-install@master
        with:
          SA_KEY: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Configure kubectl
        run: |
          yc managed-kubernetes cluster get-credentials k8s-cluster --external

      - name: Deploy to cluster
        run: |
          cd terraform
          sed -i 's/todo-react:/todo-react:${{ github.sha }}/g' service.yaml
          cat service.yaml
          kubectl apply -f service.yaml