on:
  workflow_dispatch

jobs:
#  apply-terraform:
#    name: Apply Terraform plan
#    runs-on: ubuntu-24.04
#    steps:
#      - name: Checkout repository
#        id: checkout
#        uses: actions/checkout@v6
#
#      - name: Download and setup Terraform
#        id: terraform-download
#        run: |
#          cd terraform
#          curl -L -o terraform.zip https://hashicorp-releases.yandexcloud.net/terraform/1.15.4/terraform_1.15.4_linux_amd64.zip
#          unzip terraform.zip
#          terraform version
#
#      - name: Retrieve Yandex Cloud credentials
#        id: retrieve-credentials
#        run: echo '${{ secrets.YC_SA_JSON_CREDENTIALS }} > sa-key.json
#
#      - name: Initialize Terraform
#        id: terraform-init
#        run: terraform init
#
#      - name: Validate Plan
#        id: terraform-validate
#        run: terraform validate
#
#      - name: Print Plan Changes
#        id: terraform-plan
#        run: terraform plan
#
#      - name: Apply Plan
#        id: terraform-apply
#        run: terraform apply

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v6

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Retrieve secrets & JKS
        id: jks
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          echo ${{ secrets.JKS_BASE64 }} | base64 -d - > keystore.jks

      - name: Build, tag, and push image
        id: docker-build
        env:
          CR_REGISTRY: crpd55fmd7bksog5p7vd
          CR_REPOSITORY: todo-react-test
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG -f Dockerfile.test .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Pull and run Docker image on a VM
        id: docker-deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 89.169.136.101
          username: yoo
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            curl --header Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | cut -f1 -d',' | cut -f2 -d':' | tr -d '"' | docker login --username iam --password-stdin cr.yandex
            docker run --name todo-react-test cr.yandex/crpd55fmd7bksog5p7vd/todo-react-test:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v6

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Retrieve secrets & JKS
        id: jks
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          echo ${{ secrets.JKS_BASE64 }} | base64 -d - > keystore.jks

      - name: Build, tag, and push image
        id: docker-build
        env:
          CR_REGISTRY: crpd55fmd7bksog5p7vd
          CR_REPOSITORY: todo-react
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Pull and run Docker image on a VM
        id: docker-deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 89.169.136.101
          username: yoo
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            curl --header Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | cut -f1 -d',' | cut -f2 -d':' | tr -d '"' | docker login --username iam --password-stdin cr.yandex
            docker stop todo-react || echo No container to stop
            docker system prune -a -f
            docker run -d -p 80:8080 -p 443:8443 --name todo-react cr.yandex/crpd55fmd7bksog5p7vd/todo-react:${{ github.sha }}